### ISSUE TITLE
No confines for “Stroke” setting on Format pane

### ISSUE THREAD

**Issue by amirovar** [aubrianpeters/pbivisuals#2]
1.	Go to PowerBI
2.	Import visual
3.	Import dataSet
4.	Add visual to the report
5.	Go to Format Pane
6.	Set Stroke weight = -1
7.	Set Stroke weight = 9999999999999
Actual result:
No confines
Console error in services
![image](https://cloud.githubusercontent.com/assets/12142229/18781050/e0579e0a-8188-11e6-97cd-b6c7e9654a4e.png)

Expected result: 
If value is incorrect then system highlight field or system resolves error automatically

**Comment by aubrianpeters** [comment]
Fixed in commit https://github.com/aubrianpeters/pbivisuals/commit/be0e9b30caeb2637118a28d3da11fc5d200a24ab
