### ISSUE TITLE
There are console errors then the user tries pin visual to dashboard

### ISSUE THREAD

**Issue by amirovar** [aubrianpeters/pbivisuals#4]
1.	Go to web PowerBi
2.	Import Dataset
3.	Import Visual
4.	Add visual to the report
5.	Set some values to the fields of visual
6.	Save report
7.	Pin visual to dashboard
Actual result: There are errors in console
 
[info_pin_to_dashboard.txt](https://github.com/aubrianpeters/pbivisuals/files/489278/info_pin_to_dashboard.txt)

Expected result: no errors

**Comment by aubrianpeters** [comment]
Couldn't replicate but can see how it is possible, added this commit to prevent. https://github.com/aubrianpeters/pbivisuals/commit/3d54991ddb56d5727cbdc4f011c16788803de70c
