### ISSUE TITLE
There are console errors on dashboard

### ISSUE THREAD

**Issue by amirovar** [aubrianpeters/pbivisuals#5]
1.	Go to web PowerBi
2.	Import Dataset
3.	Import Visual
4.	Add visual to the report
5.	Set some values to the fields of visual
6.	Save report
7.	Pin visual to dashboard
8.	Open dashboard
Actual result: There are errors in console
 
[info_on_dashboard.txt](https://github.com/aubrianpeters/pbivisuals/files/489281/info_on_dashboard.txt)

Expected result: no errors

**Comment by aubrianpeters** [comment]
Couldn't replicate but can see how is possible, added this commit to prevent. https://github.com/aubrianpeters/pbivisuals/commit/3d54991ddb56d5727cbdc4f011c16788803de70c
