### ISSUE TITLE
There are console then the user change size of visual

### ISSUE THREAD

**Issue by amirovar** [aubrianpeters/pbivisuals#6]
1.	Go to web PowerBi
2.	Import Dataset
3.	Import Visual
4.	Add visual to the report
5.	Set some values to the fields of visual
6.	Set small size for visual
Actual result: There are errors in console
![image](https://cloud.githubusercontent.com/assets/12142229/18781333/e8b8fcdc-8189-11e6-815b-c5a0dd44ee28.png)
[small size of visual.txt](https://github.com/aubrianpeters/pbivisuals/files/489306/small.size.of.visual.txt)

Expected result: no errors

**Comment by aubrianpeters** [comment]
Is no longer occuring with latest commit https://github.com/aubrianpeters/pbivisuals/commit/3d54991ddb56d5727cbdc4f011c16788803de70c, was unable to reproduce but believe has been fixed previously.
