### ISSUE TITLE
Published to web visual from dxt shows with error

### ISSUE THREAD

**Issue by amirovar** [aubrianpeters/pbivisuals#9]
1.	Go to dxt PowerBi
2.	Import Dataset
3.	Import Visual
4.	Add visual to the report
5.	Set some values to the fields of visual
6.	Save report
7.	Publish report to web
8.	Open report in browser
Actual result: Visual is displayed with errors
![image](https://cloud.githubusercontent.com/assets/12142229/18781439/63c320a6-818a-11e6-814d-03c5c26cea4e.png)

Expected result: Visual is shown without any errors

**Comment by aubrianpeters** [comment]
Unable to replicate. https://github.com/aubrianpeters/pbivisuals/commit/3d54991ddb56d5727cbdc4f011c16788803de70c
